---
apiVersion: v1
kind: Service
metadata:
  name: "service-factoryman"
spec:
  selector:
    app.kubernetes.io/name: factoryman
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
